### ISSUE TITLE
MySQL spamming error in console

### ISSUE THREAD

**Issue by MherZaqaryan** [MherZaqaryan/BedWars1058-Private-Games#15]
**Describe the bug**
There is an error in the console when the MySQL credentials are wrong on BedWars1058.

**Server Information (please complete the following information):**
 - OS: Windows
 - Server Software: Paper
 - Software Version: 1.8.9
 - BedWars1058 Version: 21.12.1
 - Private Games Addon: 1.1.3

**Additional context**
Error log
`
java.lang.NullPointerException
        at club.mher.privategames.NT.MY(Unknown Source) ~[?:?]
        at club.mher.privategames.PrivateGames.onDisable(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched.jar:git-PaperSpigot-"4c7641d"]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at club.mher.privategames.NT.HZ(Unknown Source) [BedWars1058-PrivateGames-1.1.4-obf-obf%20(3).jar:?]
        at club.mher.privategames.NT.kZ(Unknown Source) [BedWars1058-PrivateGames-1.1.4-obf-obf%20(3).jar:?]
        at club.mher.privategames.RV.run(Unknown Source) [BedWars1058-PrivateGames-1.1.4-obf-obf%20(3).jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
`

**Comment by MherZaqaryan** [comment]
Issue fixed, download it from here https://polymart.org/resource/1620
