### ISSUE TITLE
Private Settings dont work in BedWarsProxy

### ISSUE THREAD

**Issue by stivek69** [MherZaqaryan/BedWars1058-Private-Games#18]
**Describe the bug**
Command /private settings dont work on server with BedWarsProxy
In console i have this error 
org.bukkit.command.CommandException: Unhandled exception executing 'private settings' in club.mher.privategames.dD(private)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[server.jar:]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[server.jar:]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [server.jar:]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [server.jar:]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:762) [server.jar:]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701) [server.jar:]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604) [server.jar:]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoClassDefFoundError: com/andrei1058/bedwars/api/arena/IArena
    at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_312]
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_312]
    at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_312]
    at club.mher.privategames.mD.RF(Unknown Source) ~[?:?]
    at club.mher.privategames.mD.LG(Unknown Source) ~[?:?]
    at club.mher.privategames.mD.EG(Unknown Source) ~[?:?]
    at club.mher.privategames.vD.1(Unknown Source) ~[?:?]
    at club.mher.privategames.vD.setContents(Unknown Source) ~[?:?]
    at club.mher.privategames.api.menu.Menu.open(Unknown Source) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
    at club.mher.privategames.mD.JG(Unknown Source) ~[?:?]
    at club.mher.privategames.mD.6F(Unknown Source) ~[?:?]
    at club.mher.privategames.GE.execute(Unknown Source) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
    at club.mher.privategames.mD.GG(Unknown Source) ~[?:?]
    at club.mher.privategames.mD.VF(Unknown Source) ~[?:?]
    at club.mher.privategames.dD.execute(Unknown Source) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[server.jar:]
**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows] - Linux
 - Server Software: [e.g. Paper, Spigot] - PaperSpigot
 - Software Version: [e.g. 1.8.9] - 1.8.8
 - BedWars1058 Version: [e.g. 21.10.1] - 21.12.1
 - BedWarsProxy Version - 1.4
 - Private Games Addon: [e.g. 1.1.1] - 1.1.4

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available on the next update!
