### ISSUE TITLE
Error on plugin load

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Private-Games#34]
The plugin doesn't load even with the beta 3 on 1.17.1 / 1.18.1 server
Here is  the error

[15:48:53] [Server thread/INFO]: [BedWars1058-PrivateGames] Enabling BedWars1058-PrivateGames v1.1.7-BETA
[15:48:53] [Server thread/ERROR]: Error occurred while enabling BedWars1058-PrivateGames v1.1.7-BETA (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
	at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185) ~[?:?]
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132) ~[?:?]
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1113) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
	at club.mher.privategames.LJ.KL(Unknown Source) ~[BedWars1058-PrivateGames-1.1.7-BETA-2.jar:?]
	at club.mher.privategames.PrivateGames.onEnable(Unknown Source) ~[BedWars1058-PrivateGames-1.1.7-BETA-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-177]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-177]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalAccessException: Can not set static final club.mher.privategames.IJ field club.mher.privategames.IJ.NF to club.mher.privategames.IJ
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80) ~[?:?]
	at jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77) ~[?:?]
	at java.lang.reflect.Field.set(Field.java:799) ~[?:?]
	at club.mher.privategames.LJ.HL(Unknown Source) ~[BedWars1058-PrivateGames-1.1.7-BETA-2.jar:?]
	at club.mher.privategames.IJ.<clinit>(Unknown Source) ~[BedWars1058-PrivateGames-1.1.7-BETA-2.jar:?]
	... 20 more
[15:48:53] [Server thread/INFO]: [BedWars1058-PrivateGames] Disabling BedWars1058-PrivateGames v1.1.7-BETA
[15:48:53] [Server thread/INFO]: [BedWars1058-PrivateGames] Disabled Private Games in: 2ms

**Comment by MherZaqaryan** [comment]
Hey, this issue is already fixed and will be available in the next update!
