### ISSUE TITLE
Error connecting to the arena

### ISSUE THREAD

**Issue by K530-hub** [MherZaqaryan/BedWars1058-Private-Games#72]
**Describe the bug**
When connecting to the arena, if the player is not a member of the party, an error appears:

[21:24:57 ERROR]: Could not pass event PlayerArenaJoinEvent to BedWars1058-PrivateGames v1.1.11
java.lang.NullPointerException: Cannot invoke "de.simonsator.partyandfriends.spigot.api.party.PlayerParty.getLeader()" because the return value of "com.andrei1058.bedwars.proxy.party.PAFBungeeCordParty.getPAFParty(java.util.UUID)" is null
at com.andrei1058.bedwars.proxy.party.PAFBungeeCordParty.getOwner(PAFBungeeCordParty.java:78) ~[proxy-plugin-1.2.5 (1).jar:?]
at am.mher.privategames.QiZ3ete.j_c_sfo.kPpUW3$(Unknown Source) ~[BedWars1058-PrivateGames-1.1.11.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at com.andrei1058.bedwars.proxy.arenamanager.LegacyArena.addPlayer(LegacyArena.java:255) ~[proxy-plugin-1.2.5 (1).jar:?]
at com.andrei1058.bedwars.proxy.command.main.JoinCMD.execute(JoinCMD.java:55) ~[proxy-plugin-1.2.5 (1).jar:?]
at com.andrei1058.bedwars.proxy.command.ParentCommand.execute(ParentCommand.java:38) ~[proxy-plugin-1.2.5 (1).jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.4.jar:git-Purpur-2127]
at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.4.jar:git-Purpur-2127]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:344) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$17(ServerGamePacketListenerImpl.java:2267) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1486) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1463) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1386) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1364) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1254) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Server Information (Important):**
 - Operating System: Linux
 - Server Software: Purpur
 - Java Version: 17
 - Software Version: 1.20.4
 - Private Games Version: 1.1.11
 - BedWars1058 Version: 23.12.2
 - BedWars1058 Server Type: BUNGEE

**Comment by MherZaqaryan** [comment]
It may appear this is a Private Games issue because it has `Could not pass event PlayerArenaJoinEvent to BedWars1058-PrivateGames v1.1.11`, but it is not! Please report it to BedWarsProxy GitHub instead.
