### ISSUE TITLE
Private Games Errors with Italian Language

### ISSUE THREAD

**Issue by Xxyuri2005xX** [MherZaqaryan/BedWars1058-Private-Games#9]
**Describe the bug**
When a player is executing the command "/private settings" having the Italian language it sends an Internal error, if he starts a game ad private is not possible opening the menu

**How to reproduce**
1. Use Italian Language
2. "try typing /private settings"
3. Start agame as private and try opening the menu

**Screenshots**

**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - Server Software: [Spigot]
 - Software Version: [1.8.8]
 - BedWars1058 Version: [21.11.1]
 - Private Games Addon: [1.1.2]

**Additional context**

**Comment by MherZaqaryan** [comment]
Please provide the console errors

**Comment by Xxyuri2005xX** [comment]
[17:30:08 INFO]: Xx_yuri2005_xX issued server command: /bw lang it
[17:30:13 INFO]: Xx_yuri2005_xX issued server command: /party invite P_AymanPro4
[17:30:17 INFO]: P_AymanPro4 issued server command: /party accept Xx_yuri2005_xX
[17:30:18 INFO]: Xx_yuri2005_xX issued server command: /private
[17:30:19 INFO]: Xx_yuri2005_xX issued server command: /private
[17:30:24 INFO]: Xx_yuri2005_xX issued server command: /private settings
[17:30:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'private settings' in club.mher.privategames.cc(private)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [?:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [?:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.IllegalArgumentException: Title cannot be longer than 32 characters
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom$MinecraftInventory.<init>(CraftInventoryCustom.java:59) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom.<init>(CraftInventoryCustom.java:32) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createInventory(CraftServer.java:1525) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.Bukkit.createInventory(Bukkit.java:938) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at club.mher.privategames.bG.c() ~[?:?]
        at club.mher.privategames.b2.a() ~[?:?]
        at club.mher.privategames.cc.execute() ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 14 more

**Comment by MherZaqaryan** [comment]
Not an issue! The translation contains some message which is not permitted to be set because it was longer than 32 characters.

**Comment by Xxyuri2005xX** [comment]
ok thanks now is fixed
